export function createInitialLayerConfig() {
  return {
    Arrondissements_Brazzaville: {
      name: 'Arrondissements Brazzaville',
      visible: false,
      color: '#FF6B6B',
      opacity: 0.7,
      styleMode: 'single',
      styleField: 'name',
      labelEnabled: false,
      labelField: 'name',
      data: null,
    },
    Arrondissements_Pointe_Noire: {
      name: 'Arrondissements Pointe-Noire',
      visible: false,
      color: '#4ECDC4',
      opacity: 0.7,
      styleMode: 'single',
      styleField: 'name',
      labelEnabled: false,
      labelField: 'name',
      data: null,
    },
    Departement_Congo: {
      name: 'Departements Congo',
      visible: false,
      color: '#45B7D1',
      opacity: 0.7,
      styleMode: 'single',
      styleField: 'name',
      labelEnabled: false,
      labelField: 'name',
      data: null,
    },
    Districts_Congo: {
      name: 'Districts Congo',
      visible: false,
      color: '#96CEB4',
      opacity: 0.7,
      styleMode: 'single',
      styleField: 'name',
      labelEnabled: false,
      labelField: 'name',
      data: null,
    },
    Quartiers_kintele: {
      name: 'Quartiers Kintele',
      visible: false,
      color: '#FFEAA7',
      opacity: 0.7,
      styleMode: 'single',
      styleField: 'name',
      labelEnabled: false,
      labelField: 'name',
      data: null,
    },
  };
}
